[package]
name = "easy-fs"
version = "0.1.0"
authors = ["Yifan Wu <shinbokuow@163.com>"]
edition = "2018"

[dependencies]
spin = "0.9.0"
bitflags = "1.2.1"

device-cache = { path = "../device-cache" }
kernel-sync = {  git = "https://github.com/tkf2019/kernel-sync" }