[workspace]
members = [
    "executor",
    "easy-fs",
    "easy-fs-fuse",
    "lang",
    "lib/sharedscheduler",
    "os",
    "user_lib",
    "user_lib/macros",
    "syscall",
]
resolver = "1"
default-members = ["os"]
