[build]
target = "riscv64gc-unknown-none-elf"
incremental = false
target-dir = "../target" 

[target.riscv64gc-unknown-none-elf]
rustflags = ["-C", "link-args=-nostartfiles -Tbasic_linker.ld"]
linker = "riscv64-unknown-elf-gcc"

