[package]
name = "oscomp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
spin = "0.9"

kernel-sync = {  git = "https://github.com/tkf2019/kernel-sync" }