QEMU := "/home/zfl/u-intr/qemu-build/riscv64-softmmu/qemu-system-riscv64"
# machine, supervisor, user, echo1, echo2
# SERIAL_FLAGS := "-serial /dev/pts/4 -serial /dev/pts/5 -serial /dev/pts/5 -serial tcp::23334,server,nowait -serial tcp:localhost:23334"

TARGET := "riscv64gc-unknown-none-elf"
MODE := "release"
OBJDUMP := "rust-objdump --arch-name=riscv64"
OBJCOPY := "rust-objcopy --binary-architecture=riscv64"

BUILD_PATH := "target/" + TARGET + "/" + MODE + "/"
KERNEL_ELF := BUILD_PATH + "kernel"
KERNEL_ASM := BUILD_PATH + "kernel.asm"
KERNEL_BIN := BUILD_PATH + "kernel.bin"
KERNEL_BIN_axu15eg := BUILD_PATH + "rcore-n.bin"

clean:
    cargo clean
    cd ../sharedscheduler && cargo clean
    cd ../user && make clean && cd -

sharedscheduler:
    cd ../sharedscheduler && make build

user:
    cd ../user && make build

user_axu15eg:
    cd ../user && make build_axu15eg

build: user sharedscheduler
    LOG=debug cargo build --features "board_qemu" --release
    {{OBJCOPY}} {{KERNEL_ELF}} --strip-all -O binary {{KERNEL_BIN}}

build_axu15eg: user_axu15eg sharedscheduler
    LOG=debug cargo build --features "board_axu15eg" --release
    {{OBJCOPY}} {{KERNEL_ELF}} --strip-all -O binary {{KERNEL_BIN}}
    cp {{KERNEL_BIN}} {{KERNEL_BIN_axu15eg}}

upload: build_axu15eg
	cd /home/zfl/u-intr/opensbi && make CROSS_COMPILE=riscv64-unknown-elf- PLATFORM=axu15eg && \
	scp build/platform/axu15eg/firmware/fw_payload.bin axu15eg:~
	ssh axu15eg "./start_rocket.sh"

disasm: build
    {{OBJDUMP}} -S -t {{KERNEL_ELF}} > {{KERNEL_ASM}}

disasm_axu15eg: build_axu15eg
    {{OBJDUMP}} -S -t {{KERNEL_ELF}} > {{KERNEL_ASM}}

run: build
    {{QEMU}} -machine virt -smp 4 -nographic -bios default -kernel {{KERNEL_BIN}} 

# debug_qemu: build
#     {{QEMU}} -machine virt -smp 4 {{SERIAL_FLAGS}} -nographic -bios ./rustsbi-qemu.bin -device loader,file={{KERNEL_BIN}},addr=0x80200000 -d int -D debug.log

# debug: build disasm
#     tmux new-session -d "{{QEMU}} -machine virt -smp 4 {{SERIAL_FLAGS}} -nographic -bios ./rustsbi-qemu.bin -device loader,file={{KERNEL_BIN}},addr=0x80200000 -s -S" && tmux split-window -h "riscv64-unknown-elf-gdb -ex 'file {{KERNEL_ELF}}' -ex 'set arch riscv:rv64' -ex 'target remote localhost:1234'" && tmux -2 attach-session -d

# debug_all: build disasm
#     tmux new-session -d "{{QEMU}} -machine virt -smp 4 {{SERIAL_FLAGS}} -nographic -bios ./rustsbi-qemu.bin -device loader,file={{KERNEL_BIN}},addr=0x80200000 -d int -D debug.log -s -S" && tmux split-window -h "riscv64-unknown-elf-gdb -ex 'file {{KERNEL_ELF}}' -ex 'set arch riscv:rv64' -ex 'target remote localhost:1234'" && tmux -2 attach-session -d
