[package]
name = "errno"
categories = [
    "os",
    "error",
]
version = "0.1.0"
edition = "2021"
authors = ["TKF <kaifu6821@qq.com>"]
description = "For reporting and retrieving error conditions using the symbol errno"

[dependencies]
numeric-enum-macro = "0.2.0"