[package]
name = "time-subsys"
categories = [
    "os",
    "time",
]
version = "0.1.0"
edition = "2021"
authors = ["TKF <kaifu6821@qq.com>"]
description = "Time subsystem"

[dependencies]
numeric-enum-macro = "0.2.0"