[package]
name = "user_syscall"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time-subsys = { path = "../time-subsys"}
bitflags = "1.3.2"
